SCALE = 1
FPS = 1

CANVAS_SIZE = [1280, 720]
CANVAS_COLOR = "#1A1A1D"

MEMORY_BOARD_SIZE = [300, 650] # we'll have one for stack and one for heap
PADDING = 12

BASE_FONT_SIZE = 20

# Variable Boxes
VAR_BOX_MIN_CHAR_RATIO = [80, 30]

ARRAY_ORIENTATION = "vertical"  # "vertical" or "horizontal"
TUPLE_ORIENTATION = "vertical"  # "vertical" or "horizontal"
TUPLE_FIELD_NAME_MAX_LEN = 7

CODEBOX_BGCOLOR = "#000000"
CODEBOX_NEXT_LINE_BGCOLOR = "#4d0000"
CODEBOX_PREV_LINE_BGCOLOR = "#004d00"

# one for CustomType, other for pointer-of-CustomType
UNNAMED_COLORS = [
    "#999900", # golden
    "#8c8c8c", # gray
    "#00cccc", # cyan
    "#800000", # maroon
    "#9933ff", # purple
    "#00ccff", # sky-blue
    "#404040", # black
]

[COLOR_BY_TYPE]
IntType = "#3333ff"  # blue
BoolType = "#994d00" # brown
RealType = "#ff80ff" # pink
CharType = "#e60000" # red
ArrayOf = "#d9d9d9"  # light-gray
